model_provider = "KANDES"
model = "gpt-5.4"
model_reasoning_effort = "high"
disable_response_storage = true


[model_providers.KANDES]
name = "KANDES"
base_url = "https://api.kandes.shop/v1"
wire_api = "responses"
requires_openai_auth = true
